ls:
  src/*:
    # PascalCase = 首字母大写&驼峰
    # kebab-case = 短横线
    # camelCase = 骆驼式命令法
    # SnakeCase = 下划线
    # regex:^index = index 结尾
    .js: kebab-case | PascalCase
    .vue: PascalCase | regex:^index
    .ts: camelCase | PascalCase
    .tsx: camelCase | PascalCase
    .d.ts: kebab-case
    .mock.ts: kebab-case
    .data.ts: camelCase | kebab-case
    .test-d.ts: kebab-case
    .less: kebab-case | PascalCase
    .spec.ts: camelCase | PascalCase

ignore:
  - node_modules
  - .git
  - .circleci
  - .github
  - .vscode
  - dist
  - .local
